- name: Display user bio information from file
  hosts: localhost
  connection: local
  become: true
  # Load variables from the specified file.
  vars_files:
    - info.yml
  # Define tasks to display user bio information.  
  tasks:
  # Task to show User bio information
    - name: Show user bio details
      ansible.builtin.debug:
        msg: |
          User: {{ FIRST_NAME }} {{ LAST_NAME }}
          Date of Birth: {{ DOB }}
          Contact Number: {{ MOBILE_NUMBER }}
          Professional Details: {{ PROFESIONAL_DETAILS }}
          Skills: {{ SKILLSET }}
          Location: {{ ADDRESS }}
